Disable CGO when building bpm and test-server
After runc was updated to 1.1.11 we started getting failures like:
```
/var/vcap/data/packages/golang-1-linux/4c9041a93ce507bdc9572a0325ac35774020ee9c/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/bin/ld: /var/vcap/data/tmp/go-link-3302366506/000024.o: in function `_cgo_2cacdc9ff070_Cfunc_spawn_userns_cat':
/tmp/go-build/cgo-gcc-prolog:68: undefined reference to `spawn_userns_cat'
collect2: error: ld returned 1 exit status
```

Disabling CGO seems to resolve the problem.

Signed-off-by: Joseph Palermo <joseph.palermo@broadcom.com>
Co-authored-by: Joseph Palermo <joseph.palermo@broadcom.com>